// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2kyZbQLpZbupdFgjPtNjIRFUslmuD_cc',
    appId: '1:887795557726:web:65240b7f58f86f783e9bcf',
    messagingSenderId: '887795557726',
    projectId: 'letmeinuc-bcd70',
    authDomain: 'letmeinuc-bcd70.firebaseapp.com',
    storageBucket: 'letmeinuc-bcd70.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwvEKDFkAPhibBDIibhVhFoJDVIF3c8bA',
    appId: '1:887795557726:android:be9d7d9650e991793e9bcf',
    messagingSenderId: '887795557726',
    projectId: 'letmeinuc-bcd70',
    storageBucket: 'letmeinuc-bcd70.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDW4Fqwj6vP1EsAg1D2-3XzjnkR4UXozoo',
    appId: '1:887795557726:ios:f835dba0163eb3173e9bcf',
    messagingSenderId: '887795557726',
    projectId: 'letmeinuc-bcd70',
    storageBucket: 'letmeinuc-bcd70.appspot.com',
    iosBundleId: 'com.example.letMeInUc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDW4Fqwj6vP1EsAg1D2-3XzjnkR4UXozoo',
    appId: '1:887795557726:ios:6eada700cfaa80dc3e9bcf',
    messagingSenderId: '887795557726',
    projectId: 'letmeinuc-bcd70',
    storageBucket: 'letmeinuc-bcd70.appspot.com',
    iosBundleId: 'com.example.letMeInUc.RunnerTests',
  );
}
